### PR TITLE
Create CMakeLists.txt

### PR DESCRIPTION
**Pull request by cxwx**
for easy install

### CODE REVIEW

**Comment by tbrown122387** [comment]
@cxwx thanks for the PR. I actually had the a more complicated version of the same file already, but it hadn't pushed to the repo due to a mistake in my `.gitignore` file. Thanks for helping me uncover that!

**Comment by cxwx** [comment]
could you help make a tag.
homebrew `brew.sh` needs a version info

**Comment by cxwx** [comment]
the new tag 1.0.1-lw does not appear to contain CMakeLists.txt.

**Comment by tbrown122387** [comment]
Let’s try this again—just made v1.0.2 try that

**Comment by cxwx** [comment]
great! thanks

**Pull request closed without merging**
